version: '3'
services:

  api:
    container_name: cloudComputing_amqp_api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - EXECUTION_ENVIRONMENT=production
    ports:
      - ${API_PORT:-8080}:8080
    depends_on:
      - rabbitmq
      - redis

  worker:
    container_name: cloudComputing_amqp_worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - EXECUTION_ENVIRONMENT=production
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    container_name: cloudComputing_amqp_rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - ${RABBITMQ_PORT:-15672}:15672

  redis:
    container_name: cloudComputing_amqp_redis
    hostname: redis
    image: redis/redis-stack:latest